AllCops:
  TargetRubyVersion: 2.3

Style/Encoding:
  Enabled: false

Layout:
  Enabled: False


# frozen_string_literal: false

Metrics/MethodLength:
  Exclude:
    - 'Klass#method_with_large_hash'

Metrics/LineLength:
  Max: 120


