# .travis.yml
language: ruby

sudo: false
bundler_args: --retry=3 --jobs=3

rvm:
  - 2.3
  - 2.3.3
  - 2.4.0

script: bundle exec rspec spec || true

#matrix:
#  allow_failures:
#    - rvm: ruby-head

fast_finish: true

gemfile:
  - icinga2.gemspec
