# .travis.yml
language: ruby

sudo: required
bundler_args: --retry=3 --jobs=3

rvm:
  - 2.3
  - 2.3.3
  - 2.4.0

services:
  - docker

before_install:
  - gem install bundler
  - docker pull bodsch/docker-icinga2:1708-33.1
  - docker run --rm --detach --publish=5665:5665 --env ICINGA_MASTER=icinga2 --env ICINGA_CLUSTER=true --env ICINGA_API_USERS=root:icinga --env DEMO_DATA=true --hostname=icinga2 bodsch/docker-icinga2
  - docker ps -a

script: bundle exec rspec spec || true

fast_finish: true

gemfile:
  - Gemfile
